[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "python3", "ffmpeg"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install", "pip install openai-whisper ffmpeg-python"]

[start]
cmd = "node bot.js"
